[package]
name = "calamaris"
version = "0.1.0"
authors = ["Henk van der Laan <opensource@henkvdlaan.com>"]

[dependencies]
# Web framework
actix = "0.7"
actix-web = "0.7"
# Database ORM and Query Builder
diesel = { version = "1.3", features = ["postgres"] }
# Serialization library
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"

## BAD STUFF
# Pin Ring to slightly older for Rust 1.29.1 support
ring = "=0.13.3"
