CREATE TABLE problems (
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR(200) NOT NULL,
	statement BYTEA,
	statement_type VARCHAR(200),
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER update_problems_timestamp BEFORE UPDATE ON problems FOR EACH ROW EXECUTE PROCEDURE update_timestamp();
