CREATE TABLE teams (
	id BIGSERIAL PRIMARY KEY,
	-- Team name, used for identification.
	name VARCHAR(200) UNIQUE NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER update_teams_timestamp BEFORE UPDATE ON teams FOR EACH ROW EXECUTE PROCEDURE update_timestamp();
